# Generated by Django 6.0 on 2026-01-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='did_key',
            field=models.TextField(blank=True, help_text="The private key associated with this user's DID (in JWK format)."),
        ),
        migrations.AddField(
            model_name='user',
            name='did_method',
            field=models.CharField(default='key', help_text="The DID method used for this user's DID (e.g., 'key', 'web').", max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='vcs',
            field=models.JSONField(default=list, help_text='List of verifiable credentials associated with the user.', verbose_name='Verifiable Credentials'),
        ),
    ]
