# Generated by Django 6.0 on 2026-01-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_did_key_user_did_method_alter_user_vcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vcs',
            field=models.JSONField(default=list, help_text='List of verifiable credentials with metadata associated with the user.'),
        ),
    ]
