#!/usr/bin/env python
"""
Test script to verify the VC generated by the Generate DID & VC function.
"""

import json
import os
import sys

import didkit
import django

# Configure Django settings
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from apps.accounts.utils.did_utils import issue_vc, verify_federated_vc, verify_vc


def test_verify_generated_vc():
    """Test VC verification using the VC generated by the Generate DID & VC function."""
    # Generate a key and DID
    key = didkit.generateEd25519Key()
    did = didkit.keyToDID("key", key)

    # Create credential
    credential = {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "type": ["VerifiableCredential", "AuthenticationCredential"],
        "issuer": did,
        "issuanceDate": "2023-01-01T00:00:00Z",
        "credentialSubject": {
            "id": did,
            "name": "dcbyers13",
        },
    }

    # Issue the VC using the issue_vc function
    vc_json = issue_vc(credential, did, key)
    vc = json.loads(vc_json)

    vc_json = json.dumps(vc)

    print("VC generated by Generate DID & VC function:")
    print(json.dumps(vc, indent=2))
    print()

    # Verify the VC using verify_vc
    print("Verifying VC using verify_vc...")
    try:
        is_valid = verify_vc(vc_json)
        print(f"Verification result: {is_valid}")

        if is_valid:
            print("VC is valid!")
        else:
            print("VC is invalid!")
    except Exception as e:
        print(f"Error verifying VC: {e}")

    print()

    # Verify the VC using verify_federated_vc
    print("Verifying VC using verify_federated_vc...")
    issuer_did = vc.get("issuer")
    try:
        is_valid = verify_federated_vc(vc_json, issuer_did)
        print(f"Verification result: {is_valid}")

        if is_valid:
            print("VC is valid!")
        else:
            print("VC is invalid!")
    except Exception as e:
        print(f"Error verifying VC: {e}")


if __name__ == "__main__":
    test_verify_generated_vc()
