# Generated by Django 6.0 on 2026-01-04 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DIDMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the DID method (e.g., 'key', 'web', 'ion').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the DID method and its use cases.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this DID method is active and available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DID Method',
                'verbose_name_plural': 'DID Methods',
            },
        ),
        migrations.CreateModel(
            name='FederatedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the federated node.', max_length=100, unique=True)),
                ('endpoint', models.URLField(help_text='The endpoint URL of the federated node.', unique=True)),
                ('public_key', models.TextField(help_text='The public key of the federated node for secure communication.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this node is active and participating in the federated network.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Federated Node',
                'verbose_name_plural': 'Federated Nodes',
            },
        ),
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="The unique identifier for this DID (e.g., 'example123456789' for 'did:key:example123456789').", max_length=255)),
                ('did_uri', models.CharField(help_text="The full DID URI (e.g., 'did:key:example123456789').", max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary DID for the user.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this DID is active and available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user associated with this DID.', on_delete=django.db.models.deletion.CASCADE, related_name='dids', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(help_text='The DID method used to create this DID.', on_delete=django.db.models.deletion.PROTECT, to='core.didmethod')),
            ],
            options={
                'verbose_name': 'DID',
                'verbose_name_plural': 'DIDs',
                'unique_together': {('method', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='DIDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.JSONField(help_text='The DID Document as a JSON object.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('did', models.OneToOneField(help_text='The DID associated with this DID Document.', on_delete=django.db.models.deletion.CASCADE, related_name='document', to='core.did')),
            ],
            options={
                'verbose_name': 'DID Document',
                'verbose_name_plural': 'DID Documents',
            },
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text='The type of data that was synchronized.', max_length=50)),
                ('data_id', models.CharField(help_text='The unique identifier for the synchronized data.', max_length=255)),
                ('version', models.PositiveIntegerField(help_text='The version of the data that was synchronized.')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('conflict', 'Conflict')], help_text='The status of the synchronization event.', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the synchronization event.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(help_text='The node that sent the data.', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_sent', to='core.federatednode')),
                ('target_node', models.ForeignKey(help_text='The node that received the data.', on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_received', to='core.federatednode')),
            ],
            options={
                'verbose_name': 'Data Sync Log',
                'verbose_name_plural': 'Data Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiableCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.JSONField(help_text='The Verifiable Credential as a JSON object.')),
                ('issuer', models.CharField(help_text='The DID of the issuer of this VC.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this VC is active and valid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user to whom this VC is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='verifiable_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifiable Credential',
                'verbose_name_plural': 'Verifiable Credentials',
            },
        ),
        migrations.CreateModel(
            name='FederatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text="The type of data (e.g., 'poll', 'user_profile').", max_length=50)),
                ('data_id', models.CharField(help_text='The unique identifier for this data within its type.', max_length=255)),
                ('data', models.JSONField(help_text='The data as a JSON object.')),
                ('version', models.PositiveIntegerField(default=1, help_text='The version of this data for conflict resolution.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this data is active and synchronized.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(help_text='The federated node that owns this data.', on_delete=django.db.models.deletion.CASCADE, related_name='federated_data', to='core.federatednode')),
            ],
            options={
                'verbose_name': 'Federated Data',
                'verbose_name_plural': 'Federated Data',
                'unique_together': {('node', 'data_type', 'data_id')},
            },
        ),
    ]
