# Generated by Django 6.0 on 2026-03-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The scope type identifier (e.g., 'geographic', 'organization', 'company', 'family').", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Geographic', 'Organization', 'Company').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this scope type and its intended use.')),
                ('hierarchy_depth', models.PositiveIntegerField(default=1, help_text='Maximum depth of hierarchy for this type (1 = no sub-scopes).')),
                ('is_self_authorizing', models.BooleanField(default=False, help_text='Whether issuers can self-authorize (no parent required). True for organizations, families.')),
                ('requires_proof', models.BooleanField(default=True, help_text='Whether holders must provide proof of scope membership.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_type', models.ForeignKey(blank=True, help_text='The scope type that authorizes this one. Null for root/self-authorizing types.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_types', to='core.scopetype')),
            ],
            options={
                'verbose_name': 'Scope Type',
                'verbose_name_plural': 'Scope Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="The specific scope value (e.g., 'DeKalb County, IN', 'Acme Corp').", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_scope', models.ForeignKey(blank=True, help_text="Parent scope in hierarchy (e.g., DeKalb County's parent is Indiana).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_scopes', to='core.scope')),
                ('scope_type', models.ForeignKey(help_text='The type of this scope.', on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='core.scopetype')),
            ],
            options={
                'verbose_name': 'Scope',
                'verbose_name_plural': 'Scopes',
                'ordering': ['scope_type', 'value'],
                'unique_together': {('scope_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for this credential type (e.g., 'voting_authorization').", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Voting Authorization').", max_length=150)),
                ('description', models.TextField(blank=True)),
                ('max_issuers_per_scope', models.PositiveIntegerField(default=5, help_text='Maximum number of issuers allowed per scope.')),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether issuance requires multi-signer approval.')),
                ('min_approvals', models.PositiveIntegerField(default=1, help_text='Minimum approvals required for issuance.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_credential_type', models.ForeignKey(blank=True, help_text='Credential type required to issue this credential (e.g., StateAuthorization issues CountyAuthorization).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_credential_types', to='core.credentialtype')),
                ('scope_type', models.ForeignKey(help_text='The scope type this credential is valid for.', on_delete=django.db.models.deletion.PROTECT, related_name='credential_types', to='core.scopetype')),
            ],
            options={
                'verbose_name': 'Credential Type',
                'verbose_name_plural': 'Credential Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_did', models.CharField(help_text='The DID of the authorized issuer.', max_length=255)),
                ('authorized_by', models.CharField(help_text='The DID that authorized this issuer.', max_length=255)),
                ('authorization_credential', models.JSONField(blank=True, help_text='The credential proving authorization.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential_type', models.ForeignKey(help_text='The credential type this issuer is authorized to issue.', on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='core.credentialtype')),
                ('scope', models.ForeignKey(help_text='The scope this issuer is authorized to issue for.', on_delete=django.db.models.deletion.PROTECT, related_name='issuer_authorizations', to='core.scope')),
            ],
            options={
                'verbose_name': 'Issuer Authorization',
                'verbose_name_plural': 'Issuer Authorizations',
                'ordering': ['-created_at'],
                'unique_together': {('issuer_did', 'credential_type', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='CredentialIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.JSONField(help_text='The full Verifiable Credential as a JSON object.')),
                ('holder_did', models.CharField(help_text='The DID of the credential holder.', max_length=255)),
                ('issuer_did', models.CharField(help_text='The DID of the credential issuer.', max_length=255)),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS Content Identifier where credential is stored.', max_length=255)),
                ('blockchain_tx', models.CharField(blank=True, help_text='Blockchain transaction hash where credential hash is anchored.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', help_text='Current status of the credential.', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('credential_type', models.ForeignKey(help_text='The type of credential issued.', on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='core.credentialtype')),
                ('scope', models.ForeignKey(help_text='The scope this credential is valid for.', on_delete=django.db.models.deletion.PROTECT, related_name='credential_issuances', to='core.scope')),
            ],
            options={
                'verbose_name': 'Credential Issuance',
                'verbose_name_plural': 'Credential Issuances',
                'ordering': ['-issued_at'],
                'unique_together': {('holder_did', 'credential_type', 'scope')},
            },
        ),
    ]
