# Generated by Django 6.0 on 2026-03-12 15:34

from django.db import migrations


def create_default_scope_types(apps, schema_editor):
    """Create default scope types for geographic and organization hierarchies."""
    ScopeType = apps.get_model("core", "ScopeType")
    CredentialType = apps.get_model("core", "CredentialType")

    geographic = ScopeType.objects.create(
        name="geographic",
        display_name="Geographic",
        description="Geographic/political boundaries (town, county, state, nation, global)",
        parent_type=None,
        hierarchy_depth=5,
        is_self_authorizing=False,
        requires_proof=True,
    )

    nation = ScopeType.objects.create(
        name="nation",
        display_name="Nation",
        description="Country-level scope",
        parent_type=geographic,
        hierarchy_depth=4,
        is_self_authorizing=False,
        requires_proof=True,
    )

    state = ScopeType.objects.create(
        name="state",
        display_name="State/Province",
        description="State or province-level scope",
        parent_type=nation,
        hierarchy_depth=3,
        is_self_authorizing=False,
        requires_proof=True,
    )

    county = ScopeType.objects.create(
        name="county",
        display_name="County",
        description="County-level scope",
        parent_type=state,
        hierarchy_depth=2,
        is_self_authorizing=False,
        requires_proof=True,
    )

    town = ScopeType.objects.create(
        name="town",
        display_name="Town/Municipality",
        description="Town or municipality-level scope",
        parent_type=county,
        hierarchy_depth=1,
        is_self_authorizing=False,
        requires_proof=True,
    )

    organization = ScopeType.objects.create(
        name="organization",
        display_name="Organization",
        description="General organization scope (companies, teams, clubs)",
        parent_type=None,
        hierarchy_depth=3,
        is_self_authorizing=True,
        requires_proof=True,
    )

    company = ScopeType.objects.create(
        name="company",
        display_name="Company",
        description="Company or business scope",
        parent_type=organization,
        hierarchy_depth=2,
        is_self_authorizing=True,
        requires_proof=True,
    )

    department = ScopeType.objects.create(
        name="department",
        display_name="Department",
        description="Department within an organization",
        parent_type=company,
        hierarchy_depth=1,
        is_self_authorizing=True,
        requires_proof=True,
    )

    family = ScopeType.objects.create(
        name="family",
        display_name="Family",
        description="Family unit scope",
        parent_type=None,
        hierarchy_depth=1,
        is_self_authorizing=True,
        requires_proof=True,
    )

    club = ScopeType.objects.create(
        name="club",
        display_name="Club/Group",
        description="Club, group, or organization scope",
        parent_type=None,
        hierarchy_depth=1,
        is_self_authorizing=True,
        requires_proof=True,
    )

    CredentialType.objects.create(
        name="voting_authorization",
        display_name="Voting Authorization",
        description="Authorization to vote in polls within a specific scope",
        scope_type=town,
        parent_credential_type=None,
        max_issuers_per_scope=10,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="county_voting_authorization",
        display_name="County Voting Authorization",
        description="Authorization to vote in county-level polls",
        scope_type=county,
        parent_credential_type=None,
        max_issuers_per_scope=10,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="state_voting_authorization",
        display_name="State Voting Authorization",
        description="Authorization to vote in state-level polls",
        scope_type=state,
        parent_credential_type=None,
        max_issuers_per_scope=10,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="nation_voting_authorization",
        display_name="Nation Voting Authorization",
        description="Authorization to vote in national polls",
        scope_type=nation,
        parent_credential_type=None,
        max_issuers_per_scope=10,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="global_voting_authorization",
        display_name="Global Voting Authorization",
        description="Authorization to vote in global polls",
        scope_type=geographic,
        parent_credential_type=None,
        max_issuers_per_scope=10,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="company_membership",
        display_name="Company Membership",
        description="Membership credential for company members",
        scope_type=company,
        parent_credential_type=None,
        max_issuers_per_scope=5,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="family_membership",
        display_name="Family Membership",
        description="Membership credential for family members",
        scope_type=family,
        parent_credential_type=None,
        max_issuers_per_scope=2,
        requires_approval=False,
        min_approvals=1,
    )

    CredentialType.objects.create(
        name="club_membership",
        display_name="Club Membership",
        description="Membership credential for club members",
        scope_type=club,
        parent_credential_type=None,
        max_issuers_per_scope=5,
        requires_approval=False,
        min_approvals=1,
    )


def reverse_migration(apps, schema_editor):
    """Remove all default scope types and credential types."""
    ScopeType = apps.get_model("core", "ScopeType")
    CredentialType = apps.get_model("core", "CredentialType")

    CredentialType.objects.filter(
        name__in=[
            "voting_authorization",
            "county_voting_authorization",
            "state_voting_authorization",
            "nation_voting_authorization",
            "global_voting_authorization",
            "company_membership",
            "family_membership",
            "club_membership",
        ]
    ).delete()

    ScopeType.objects.filter(
        name__in=[
            "geographic",
            "nation",
            "state",
            "county",
            "town",
            "organization",
            "company",
            "department",
            "family",
            "club",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_scopes_and_credentials"),
    ]

    operations = [
        migrations.RunPython(create_default_scope_types, reverse_migration),
    ]
