# Generated by Django 6.0 on 2026-03-12 16:00

from django.db import migrations


def create_default_did_methods(apps, schema_editor):
    """Create default DID methods."""
    DIDMethod = apps.get_model("core", "DIDMethod")

    DIDMethod.objects.get_or_create(
        name="key",
        defaults={
            "description": "DID method using a raw key. Simple, self-contained, no blockchain.",
            "is_active": True,
        },
    )

    DIDMethod.objects.get_or_create(
        name="ethr",
        defaults={
            "description": "DID method using the Ethereum blockchain. Enables on-chain identity with smart contract integration.",
            "is_active": True,
        },
    )

    DIDMethod.objects.get_or_create(
        name="web",
        defaults={
            "description": "DID method using DNS and HTTPS. Maps domain names to DIDs.",
            "is_active": True,
        },
    )

    DIDMethod.objects.get_or_create(
        name="ion",
        defaults={
            "description": "DID method using IPFS and Sidetree protocol. Scalable, no gas fees.",
            "is_active": True,
        },
    )


def reverse_migration(apps, schema_editor):
    """Remove default DID methods."""
    DIDMethod = apps.get_model("core", "DIDMethod")
    DIDMethod.objects.filter(name__in=["key", "ethr", "web", "ion"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_populate_default_scope_types"),
    ]

    operations = [
        migrations.RunPython(create_default_did_methods, reverse_migration),
    ]
