# Generated by Django 6.0 on 2026-03-12 20:27

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_did_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this message.', unique=True)),
                ('message_type', models.CharField(choices=[('announce', 'Announce'), ('request', 'Request'), ('response', 'Response'), ('vote', 'Vote'), ('credential', 'Credential'), ('poll', 'Poll'), ('merkle_update', 'Merkle Update'), ('ping', 'Ping'), ('pong', 'Pong')], help_text='The type of sync message.', max_length=20)),
                ('sender_endpoint', models.URLField(blank=True, help_text='The endpoint URL of the sending node.', max_length=500)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, help_text='When the message was created.')),
                ('signature', models.TextField(blank=True, help_text='Signature of the message by the sender node.')),
                ('payload', models.JSONField(help_text='The message payload containing data and metadata.')),
                ('previous_hash', models.CharField(blank=True, help_text='Hash of the previous message for chain integrity.', max_length=128)),
                ('proof_of_work', models.PositiveIntegerField(default=0, help_text='Proof of work nonce for message validation.')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this message has been processed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_node', models.ForeignKey(help_text='The node that sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.federatednode')),
            ],
            options={
                'verbose_name': 'Sync Message',
                'verbose_name_plural': 'Sync Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message_type'], name='core_syncme_message_12cdd6_idx'), models.Index(fields=['sender_node', 'timestamp'], name='core_syncme_sender__b65dde_idx'), models.Index(fields=['is_processed'], name='core_syncme_is_proc_66be38_idx')],
            },
        ),
    ]
