# Generated by Django 6.0 on 2026-03-12 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_syncmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorser_did', models.CharField(help_text='The DID of the issuer giving the endorsement.', max_length=255)),
                ('endorsed_issuer_did', models.CharField(help_text='The DID of the issuer being endorsed.', max_length=255)),
                ('is_positive', models.BooleanField(default=True, help_text='Whether this is a positive endorsement.')),
                ('comment', models.TextField(blank=True, help_text='Optional comment about the endorsement.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this endorsement is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(help_text='The scope of the endorsement.', on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='core.scope')),
            ],
            options={
                'verbose_name': 'Issuer Endorsement',
                'verbose_name_plural': 'Issuer Endorsements',
                'ordering': ['-created_at'],
                'unique_together': {('endorser_did', 'endorsed_issuer_did', 'scope')},
            },
        ),
        migrations.CreateModel(
            name='IssuerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_did', models.CharField(help_text='The DID of the issuer.', max_length=255)),
                ('total_credentials_issued', models.PositiveIntegerField(default=0, help_text='Total number of credentials issued.')),
                ('unique_holders', models.PositiveIntegerField(default=0, help_text='Number of unique credential holders.')),
                ('credentials_this_month', models.PositiveIntegerField(default=0, help_text='Credentials issued in the current month.')),
                ('credentials_revoked', models.PositiveIntegerField(default=0, help_text='Number of credentials revoked.')),
                ('verifications_attempted', models.PositiveIntegerField(default=0, help_text='Number of verification attempts.')),
                ('verifications_successful', models.PositiveIntegerField(default=0, help_text='Number of successful verifications.')),
                ('scope_violations', models.PositiveIntegerField(default=0, help_text='Number of out-of-scope issuances.')),
                ('first_issuance', models.DateTimeField(blank=True, help_text='When the first credential was issued.', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time metrics were updated.')),
                ('scope', models.ForeignKey(help_text='The scope these metrics apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='issuer_metrics', to='core.scope')),
            ],
            options={
                'verbose_name': 'Issuer Metrics',
                'verbose_name_plural': 'Issuer Metrics',
                'ordering': ['-last_updated'],
                'unique_together': {('issuer_did', 'scope')},
            },
        ),
    ]
