#!/usr/bin/env python
"""
Test suite for Verifiable Credential (VC) verification functionality.

This script tests VC verification using:
1. Direct didkit verification (didkit.verifyCredential)
2. Custom utility functions (verify_vc, verify_federated_vc)
"""

import json
import os

import didkit
import django

from apps.accounts.utils.did_utils import issue_vc, verify_federated_vc, verify_vc

# Configure Django settings
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

django.setup()


def test_didkit_direct_verification():
    """Test VC verification using didkit.verifyCredential directly."""
    print("=== Testing Direct DIDKit Verification ===")

    # Load test VC from fixtures
    fixture_path = os.path.join(os.path.dirname(__file__), "../fixtures/test_vc.json")
    with open(fixture_path, "r") as f:
        vc_json = f.read()

    print("VC JSON:")
    print(vc_json)
    print()

    # Verify the VC using didkit
    try:
        result = didkit.verifyCredential(vc_json, "{}")
        result = json.loads(result)
        print(f"Verification result: {result}")
        print(f"Verification errors: {result.get('errors')}")
        print(f"Verification warnings: {result.get('warnings')}")
        print(f"Verification checks: {result.get('checks')}")
        print(f"Verification status: {not result.get('errors')}")

        # Assert no errors
        assert not result.get("errors"), (
            f"VC verification failed: {result.get('errors')}"
        )
        print("✅ VC verification successful using didkit.verifyCredential")
        return True
    except Exception as e:
        print(f"❌ Failed to verify VC: {e}")
        return False


def test_custom_utility_verification():
    """Test VC verification using custom utility functions."""
    print("\n=== Testing Custom Utility Verification ===")

    # Generate a key and DID
    key = didkit.generateEd25519Key()
    did = didkit.keyToDID("key", key)

    # Create credential
    credential = {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "type": ["VerifiableCredential", "AuthenticationCredential"],
        "issuer": did,
        "issuanceDate": "2023-01-01T00:00:00Z",
        "credentialSubject": {
            "id": did,
            "name": "dcbyers13",
        },
    }

    # Issue the VC using the issue_vc function
    vc_json = issue_vc(credential, did, key)
    vc = json.loads(vc_json)
    print("VC generated by issue_vc function:")
    print(json.dumps(vc, indent=2))
    print()

    # Test verify_vc
    print("Verifying VC using verify_vc...")
    try:
        is_valid = verify_vc(vc_json, did_key=json.loads(key))
        print(f"Verification result: {is_valid}")

        if is_valid:
            print("✅ VC is valid using verify_vc!")
        else:
            print("❌ VC is invalid using verify_vc!")
            return False
    except Exception as e:
        print(f"❌ Error verifying VC with verify_vc: {e}")
        return False

    # Test verify_federated_vc
    print("\nVerifying VC using verify_federated_vc...")
    issuer_did = vc.get("issuer")
    try:
        is_valid = verify_federated_vc(vc_json, issuer_did, did_key=json.loads(key))
        print(f"Verification result: {is_valid}")

        if is_valid:
            print("✅ VC is valid using verify_federated_vc!")
        else:
            print("❌ VC is invalid using verify_federated_vc!")
            return False
    except Exception as e:
        print(f"❌ Error verifying VC with verify_federated_vc: {e}")
        return False

    return True


def test_edge_cases():
    """Test edge cases for VC verification."""
    print("\n=== Testing Edge Cases ===")

    # Generate a key and DID
    key = didkit.generateEd25519Key()
    did = didkit.keyToDID("key", key)

    # Test 1: VC with minimal fields
    print("Test 1: VC with minimal fields...")
    minimal_credential = {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "type": ["VerifiableCredential"],
        "issuer": did,
        "issuanceDate": "2023-01-01T00:00:00Z",
        "credentialSubject": {"id": did},
    }

    vc_json = issue_vc(minimal_credential, did, key)
    try:
        is_valid = verify_vc(vc_json, did_key=json.loads(key))
        if is_valid:
            print("✅ Minimal VC is valid!")
        else:
            print("❌ Minimal VC is invalid!")
            return False
    except Exception as e:
        print(f"❌ Error verifying minimal VC: {e}")
        return False

    # Test 2: VC with special characters
    print("\nTest 2: VC with special characters...")
    special_credential = {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "type": ["VerifiableCredential"],
        "issuer": did,
        "issuanceDate": "2023-01-01T00:00:00Z",
        "credentialSubject": {
            "id": did,
            "name": "John O'Brien-Smith",
            "email": "john.o'brien@example.com",
        },
    }

    vc_json = issue_vc(special_credential, did, key)
    try:
        is_valid = verify_vc(vc_json, did_key=json.loads(key))
        if is_valid:
            print("✅ VC with special characters is valid!")
        else:
            print("❌ VC with special characters is invalid!")
            return False
    except Exception as e:
        print(f"❌ Error verifying VC with special characters: {e}")
        return False

    return True


if __name__ == "__main__":
    print("Running VC verification tests...\n")

    success = True

    # Run direct didkit verification test
    if not test_didkit_direct_verification():
        success = False

    # Run custom utility verification test
    if not test_custom_utility_verification():
        success = False

    # Run edge case tests
    if not test_edge_cases():
        success = False

    if success:
        print("\n🎉 All VC verification tests passed!")
    else:
        print("\n❌ Some VC verification tests failed.")
        exit(1)
