from pathlib import Path

import environ

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

env = environ.Env(
    POLY_DEBUG=(bool, True),
    POLY_ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    GUNICORN_WORKERS=(int, 4),
)

environ.Env.read_env()

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.poller": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "apps.accounts": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings — unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = env.str(
    "POLY_SECRET_KEY",
    default="django-insecure-krg5-y#ck3o%elpl_nwsv1!+a+g6b0g&3pa%7kx=)yh47ylh_#",
)

DEBUG = env.bool("POLY_DEBUG")

if DEBUG:
    INTERNAL_IPS = ["127.0.0.1"]

ALLOWED_HOSTS = env.list("POLY_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.core.apps.CoreConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.poller.apps.PollerConfig",
    "mozilla_django_oidc",
]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "mozilla_django_oidc.middleware.SessionRefresh",
]

if DEBUG:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "apps" / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database — Postgres via DATABASE_URL, fallback to sqlite
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    ),
}


# Password validation disabled — all auth is OIDC/DID based
AUTH_PASSWORD_VALIDATORS = []

AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.MyOIDCAuthenticationBackend",
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "apps" / "core" / "static"]
STATIC_ROOT = env.str("POLY_STATIC_ROOT", default=str(BASE_DIR / "staticfiles"))
MEDIA_ROOT = env.str("POLY_MEDIA_ROOT", default=str(BASE_DIR / "media"))

# Authentication
LOGIN_REDIRECT_URL = "poll_list"
LOGOUT_REDIRECT_URL = "poll_list"
LOGIN_URL = "oidc_authentication_init"

# Session cookie — unique name to prevent collisions with WUN/IdP on 127.0.0.1
SESSION_COOKIE_NAME = "poly_sessionid"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_DOMAIN = None
SESSION_SAVE_EVERY_REQUEST = True

# OIDC Settings
OIDC_RP_CLIENT_ID = "099120"
OIDC_RP_CLIENT_SECRET = "59b0d3aa8f6f5ff82384c6d4502420f72688d36267added38db4d68c"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_VERIFY_KID = False

# All OIDC endpoints use 127.0.0.1:8000 (the IdP) — configurable via env
OIDC_OP_AUTHORIZATION_ENDPOINT = env.str(
    "OIDC_OP_AUTHORIZATION_ENDPOINT",
    default="http://127.0.0.1:8000/openid/authorize/",
)
OIDC_OP_TOKEN_ENDPOINT = env.str(
    "OIDC_OP_TOKEN_ENDPOINT",
    default="http://127.0.0.1:8000/openid/token/",
)
OIDC_OP_USER_ENDPOINT = env.str(
    "OIDC_OP_USER_ENDPOINT",
    default="http://127.0.0.1:8000/openid/userinfo/",
)
OIDC_OP_JWKS_ENDPOINT = env.str(
    "OIDC_OP_JWKS_ENDPOINT",
    default="http://127.0.0.1:8000/openid/jwks/",
)

# Callback must use 127.0.0.1 to match session domain
OIDC_RP_CALLBACK_URL = "http://127.0.0.1:8002/oidc/callback/"

# Treat sub claim as DID — map directly to username
OIDC_USERNAME_ALGO = lambda claims: claims.get("sub")

# Bypass email requirement — we use DIDs, not email
OIDC_RP_REQUIRED_CLAIMS = []
OIDC_VERIFY_SSL = False
OIDC_STORE_ID_TOKEN = True

# Federated Identity and Trust Management
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/

# Trust model configuration
# REQUIRE_TRUSTED_ISSUERS = False  # Set to True to enable trusted issuer list
# TRUSTED_ISSUERS = []  # List of trusted issuer DIDs when REQUIRE_TRUSTED_ISSUERS is True

# Open trust model by default (allow any federated server)
# This can be changed to a more restrictive model in production
