# Generated by Django 6.0 on 2026-01-04 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the geographical scope (e.g., 'local', 'state', 'national', 'global').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the geographical scope and its use cases.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this geographical scope is active and available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geographical Scope',
                'verbose_name_plural': 'Geographical Scopes',
            },
        ),
        migrations.CreateModel(
            name='FederatedPoll',
            fields=[
            ],
            options={
                'verbose_name': 'Federated Poll',
                'verbose_name_plural': 'Federated Polls',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.federateddata',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the poll.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the poll.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this poll is active and available for voting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this poll.', on_delete=django.db.models.deletion.PROTECT, related_name='polls_created', to=settings.AUTH_USER_MODEL)),
                ('geographical_scope', models.ForeignKey(help_text='The geographical scope of this poll.', on_delete=django.db.models.deletion.PROTECT, to='poller.geographicalscope')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text of the poll option.', max_length=255)),
                ('votes', models.PositiveIntegerField(default=0, help_text='Number of votes this option has received.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(help_text='The poll to which this option belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poller.poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'unique_together': {('poll', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(help_text='The option that was voted for.', on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='poller.polloption')),
                ('poll', models.ForeignKey(help_text='The poll in which this vote was cast.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poller.poll')),
                ('user', models.ForeignKey(help_text='The user who cast this vote.', on_delete=django.db.models.deletion.PROTECT, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'unique_together': {('poll', 'user')},
            },
        ),
    ]
