# Generated by Django 6.0 on 2026-03-12 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_did_methods'),
        ('poller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='geographical_scope',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poll',
            name='blockchain_anchor',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash anchoring this poll.', max_length=255),
        ),
        migrations.AddField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='When the poll ends. Null for no end time.', null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='ipfs_cid',
            field=models.CharField(blank=True, help_text='IPFS Content Identifier for poll data.', max_length=255),
        ),
        migrations.AddField(
            model_name='poll',
            name='min_issuer_trust_score',
            field=models.FloatField(default=0.0, help_text='Minimum trust score for credential issuers (0.0 - 1.0).'),
        ),
        migrations.AddField(
            model_name='poll',
            name='require_multiple_issuers',
            field=models.BooleanField(default=False, help_text='Require credentials from multiple issuers.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='required_credential_type',
            field=models.ForeignKey(blank=True, help_text='The credential type required to vote in this poll.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polls_requiring_credential', to='core.credentialtype'),
        ),
        migrations.AddField(
            model_name='poll',
            name='required_scope',
            field=models.ForeignKey(blank=True, help_text='The specific scope value required to vote.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polls_requiring_scope', to='core.scope'),
        ),
        migrations.AddField(
            model_name='poll',
            name='required_scope_type',
            field=models.ForeignKey(blank=True, help_text='The scope type required to vote in this poll.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polls_requiring_scope', to='core.scopetype'),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_count_anchor',
            field=models.CharField(blank=True, help_text='Blockchain anchor for vote count.', max_length=255),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_weight',
            field=models.PositiveIntegerField(default=1, help_text='Vote weight per voter. Always 1 for equal voting.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes_merkle_root',
            field=models.CharField(blank=True, help_text='Merkle root of all votes for verification.', max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='blockchain_tx',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash for this vote.', max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='credential_cid',
            field=models.CharField(blank=True, help_text="IPFS CID of voter's voting credential.", max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='credential_proof',
            field=models.JSONField(blank=True, default=dict, help_text='Zero-knowledge proof of credential possession.'),
        ),
        migrations.AddField(
            model_name='vote',
            name='ipfs_cid',
            field=models.CharField(blank=True, help_text='IPFS Content Identifier for this vote.', max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this vote has been cryptographically verified.'),
        ),
        migrations.AddField(
            model_name='vote',
            name='signature',
            field=models.TextField(blank=True, help_text="Cryptographic signature from voter's DID key."),
        ),
        migrations.AddField(
            model_name='vote',
            name='verification_details',
            field=models.JSONField(blank=True, default=dict, help_text='Details about vote verification.'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_did',
            field=models.CharField(blank=True, help_text='The DID of the voter.', max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Weight of this vote. Always 1 for equal voting.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who cast this vote.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes_cast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voter_did')},
        ),
        migrations.DeleteModel(
            name='GeographicalScope',
        ),
    ]
