# Generated by Django 6.0.4 on 2026-04-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0002_add_scoped_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='embedding_app',
            field=models.CharField(blank=True, help_text="Embedding application identifier (e.g., 'byers-brands-llc', 'namechart').", max_length=100),
        ),
        migrations.AddField(
            model_name='poll',
            name='funding_current',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current funding amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='poll',
            name='funding_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for funding before proposal expires.', null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='funding_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Funding goal for proposal.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_proposal',
            field=models.BooleanField(default=False, help_text='Whether this is a proposal requiring funding.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='parent_poll',
            field=models.ForeignKey(blank=True, help_text='Parent poll for hierarchical family/organization polls.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_polls', to='poller.poll'),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('public', 'Public'), ('family_scoped', 'Family-Scoped'), ('family_unit', 'Family-Unit'), ('organization', 'Organization')], default='public', help_text='Type of poll determining visibility and authorization rules.', max_length=20),
        ),
        migrations.AddField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='When the poll starts. Null for immediate activation.', null=True),
        ),
    ]
