# Generated by Django 6.0.4 on 2026-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0003_extend_poll_for_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='vote_weight',
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_power_ratio',
            field=models.FloatField(default=1.0, help_text='The multiplier for voting power if using a custom rule.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_power_rule',
            field=models.CharField(default='1:1', help_text="The rule defining voting power calculation (e.g., '1:1', 'investor_share').", max_length=50),
        ),
    ]
