# Generated by Django 6.0.4 on 2026-05-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0004_remove_poll_vote_weight_poll_vote_power_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='merkle_root',
            field=models.CharField(blank=True, help_text='Merkle root of vote batch for cryptographic verification.', max_length=255, null=True),
        ),
    ]
