# Generated by Django 6.0.4 on 2026-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0006_make_vote_signature_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_mutable',
            field=models.BooleanField(default=False, help_text='Allow a DID to overwrite their previous vote checkpoint.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='temporal_type',
            field=models.CharField(choices=[('timed', 'Timed'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing')], default='timed', help_text='Temporal schedule classification: timed, scheduled, or ongoing.', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_current',
            field=models.BooleanField(default=True, help_text="Whether this vote is the voter's active checkpoint. When a DID re-votes on a mutable poll the previous record is flipped to False and a new record is ingested."),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='votes',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED — use dynamic_vote_count instead.'),
        ),
    ]
