# Generated by Django 5.2.8 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0007_temporal_poll_states'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poll',
            name='allow_write_ins',
            field=models.BooleanField(default=False, help_text='Allow voters to submit write-in ballot options.'),
        ),
        migrations.AddField(
            model_name='poll',
            name='write_in_display_limit',
            field=models.PositiveIntegerField(default=5, help_text='Max write-in options shown in the leaderboard.'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='is_write_in',
            field=models.BooleanField(default=False, help_text='Whether this is a crowd-sourced write-in option.'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='nominated_by',
            field=models.CharField(blank=True, help_text='DID of the voter who first proposed this write-in.', max_length=255, null=True),
        ),
    ]
