# Generated by Django 5.2.8 on 2026-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0008_write_in_ballot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='credential_data',
            field=models.JSONField(blank=True, help_text='Stores the un-blinded verification credential proof package passed during ingestion.', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='required_credential_type',
            field=models.CharField(blank=True, help_text="The identity credential required to vote in this poll (e.g., 'municipal_voter').", max_length=100, null=True),
        ),
    ]
