# Generated by Django 6.0.4 on 2026-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0009_credential_gate_unified'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='min_fidelity_required',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum trust fidelity required (1=Social/Peer, 2=Institutional, 3=Hardware/Security).'),
        ),
    ]
