# Generated by Django 6.0.4 on 2026-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0010_add_min_fidelity_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevocationAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_did', models.CharField(help_text='DID of the issuer who originally issued the credential.', max_length=255)),
                ('subject_did', models.CharField(db_index=True, help_text='DID of the credential subject (voter) whose credential is revoked.', max_length=255)),
                ('original_credential_id', models.CharField(blank=True, default='', help_text='Optional identifier of the specific credential being revoked.', max_length=512)),
                ('signature', models.TextField(help_text='Base58btc-encoded Ed25519 signature proving the issuer authorised this revocation.')),
                ('timestamp', models.DateTimeField(help_text='When the revocation was issued (ISO-8601).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Revocation Attestation',
                'verbose_name_plural': 'Revocation Attestations',
                'indexes': [models.Index(fields=['issuer_did', 'subject_did'], name='poller_revo_issuer__dd568d_idx')],
            },
        ),
    ]
