# Generated by Django 6.0.4 on 2026-05-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0011_add_revocation_attestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_did', models.CharField(help_text='DID of the issuer authorised to issue credentials for this poll.', max_length=255)),
                ('poll', models.ForeignKey(help_text='The poll this whitelist entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='trusted_issuers', to='poller.poll')),
            ],
            options={
                'verbose_name': 'Trusted Issuer',
                'verbose_name_plural': 'Trusted Issuers',
                'unique_together': {('poll', 'issuer_did')},
            },
        ),
    ]
