# Generated by Django 6.0.4 on 2026-05-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0012_add_trusted_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedissuer',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='If True, this issuer is treated as a constitutional registrar for this poll and bypasses the per-poll whitelist.'),
        ),
    ]
