# Generated by Django 6.0.4 on 2026-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0013_add_trusted_issuer_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='nostr_event_id',
            field=models.CharField(blank=True, help_text='SHA-256 event ID of the originating Nostr event (kind:30023).', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='nostr_pubkey',
            field=models.CharField(blank=True, help_text='Pubkey hex of the Nostr event creator.', max_length=64),
        ),
        migrations.AddField(
            model_name='vote',
            name='nostr_event_id',
            field=models.CharField(blank=True, help_text='SHA-256 event ID of the originating Nostr vote event (kind:1112).', max_length=64, null=True, unique=True),
        ),
    ]
